from lib.exceptions.exceptions import DataRealError